function out1 = invertedPendulumAndCart(in1,F_x,in3)
%invertedPendulumAndCart
%    OUT1 = invertedPendulumAndCart(IN1,F_x,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    18-Jan-2024 16:14:59

%    states = [x theta v omega]
%    inputs = [F_x]
%    params = [g l m_c m_p]
%
g = in3(1,:);
l = in3(2,:);
m_c = in3(3,:);
m_p = in3(4,:);
omega = in1(4,:);
theta = in1(2,:);
v = in1(3,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = m_c+m_p;
t5 = l.^2;
t6 = m_p.^2;
t7 = omega.^2;
t8 = t2.^2;
t9 = m_p.*t4.*t5;
t10 = l.*m_p.*t3.*t7;
t11 = F_x+t10;
t12 = -t9;
t13 = t5.*t6.*t8;
t14 = t12+t13;
t15 = -1.0./(t9-t13);
out1 = [v;omega;(m_p.*t5.*t11)./(t9-t13)+(g.*t2.*t3.*t5.*t6)./(t9-t13);l.*m_p.*t2.*t11.*t15+g.*l.*m_p.*t3.*t4.*t15];
