function setObjective(obj,lagrange_fun,mayer_fun)
    arguments
        obj (1,1) trajopt.collocation.Program;
        lagrange_fun (1,1) function_handle;
        mayer_fun (1,1) function_handle = @(x0,t0,xf,tf)0;
    end
    x = casadi.MX.sym('x',obj.NumStates);
    u = casadi.MX.sym('u',obj.NumControls);
    p = casadi.MX.sym('p',obj.NumParameters);

    obj.LagrangeCost = casadi.Function( ...
        'lagrangeCost', ...
        {x,u,p}, ...
        {lagrange_fun(x,u,p)}, ...
        {'x','u','p'}, ...
        {'Jl'} ...
        );

    x0 = casadi.MX.sym('x0',obj.NumStates);
    t0 = casadi.MX.sym('t0',1);
    xf = casadi.MX.sym('xf',obj.NumStates);
    tf = casadi.MX.sym('tf',1);

    obj.MayerCost = casadi.Function( ...
        'mayerCost', ...
        {x0,t0,xf,tf}, ...
        {mayer_fun(x0,t0,xf,tf)}, ...
        {'x0','t0','xf','tf'}, ...
        {'Jm'} ...
        );
end