function A = slipAngleMatrix(in1)
%slipAngleMatrix
%    A = slipAngleMatrix(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    18-Jul-2025 14:44:53

V = in1(15,:);
a = in1(16,:);
a_n = in1(17,:);
b = in1(18,:);
rho_r = in1(57,:);
t_f = in1(58,:);
t_r = in1(59,:);
varepsilon = in1(60,:);
t2 = cos(varepsilon);
t3 = 1.0./V;
A = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-t2,0.0,(t3.*(a-a_n+b.*t2))./t2,t3,t3,rho_r.*t3,t3.*(rho_r-t_f+t_r),0.0,-t3.*(a_n-t_f.*sin(varepsilon))],[2,9]);
end
