function b = slipAngleVector(in1)
%slipAngleVector
%    B = slipAngleVector(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    18-Jul-2025 14:44:53

b = [0.0;0.0];
end
