function out1 = dynamicBicycleStateMatrix(in1,in2)
%dynamicBicycleStateMatrix
%    OUT1 = dynamicBicycleStateMatrix(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    03-Apr-2024 12:36:07

%    states = [x y psi v_x v_y omega_z]
%    params = [C_f C_r I_zz l_f l_r m]
%
C_f = in2(1,:);
C_r = in2(2,:);
I_zz = in2(3,:);
l_f = in2(4,:);
l_r = in2(5,:);
m = in2(6,:);
v_x = in1(4,:);
t2 = 1.0./I_zz;
t3 = 1.0./m;
t4 = 1.0./v_x;
t5 = C_f.*l_f.*t4.*2.0;
t6 = C_r.*l_r.*t4.*2.0;
t7 = -t6;
out1 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,v_x,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,-t3.*(C_f.*t4.*2.0+C_r.*t4.*2.0),-t2.*(t5+t7),0.0,0.0,1.0,0.0,-t3.*(t5+t7+m.*v_x),-t2.*(l_f.*t5+l_r.*t6)],[6,6]);
