function out1 = pendulumStateMatrix(in1,in2)
%pendulumStateMatrix
%    OUT1 = pendulumStateMatrix(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    05-Jun-2024 14:37:14

%    states = [theta omega]
%    params = [b g l m]
%
b = in2(1,:);
g = in2(2,:);
l = in2(3,:);
m = in2(4,:);
out1 = reshape([0.0,-g./l,1.0,-(b.*1.0./l.^2)./m],[2,2]);
