function out1 = rollingDiskKinematicRates(in1,in2,in3)
%rollingDiskKinematicRates
%    OUT1 = rollingDiskKinematicRates(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    08-Feb-2024 23:08:18

psi = in1(3,:);
r = in3(3,:);
u_1 = in2(1,:);
out1 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-r.*u_1.*sin(psi),r.*u_1.*cos(psi),0.0,0.0,0.0],[5,3]);
