function out1 = rollingDiskSpeedJacobian(in1,in2)
%rollingDiskSpeedJacobian
%    OUT1 = rollingDiskSpeedJacobian(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    13-Feb-2024 23:02:38

psi = in1(3,:);
r = in2(3,:);
out1 = reshape([0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,r.*cos(psi),r.*sin(psi),0.0,0.0,1.0],[5,3]);
