function out1 = rollingDiskKinematics(in1,in2,in3)
%rollingDiskKinematics
%    OUT1 = rollingDiskKinematics(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    10-Feb-2024 23:26:28

psi = in1(3,:);
r = in3(3,:);
u_1 = in2(1,:);
u_2 = in2(2,:);
u_3 = in2(3,:);
out1 = [r.*u_3.*cos(psi);r.*u_3.*sin(psi);u_1;u_2;u_3];
