function out1 = rollingDiskKinematics(in1,in2,in3)
%rollingDiskKinematics
%    OUT1 = rollingDiskKinematics(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    08-Feb-2024 23:08:18

psi = in1(3,:);
r = in3(3,:);
out1 = reshape([0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,r.*cos(psi),r.*sin(psi),0.0,0.0,1.0],[5,3]);
