function out1 = rollingDiskRateJacobian(in1,in2)
%rollingDiskRateJacobian
%    OUT1 = rollingDiskRateJacobian(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    12-Feb-2024 23:02:49

out1 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0],[3,5]);
