function out1 = rollingDiskKinematicRates(in1,in2,in3,in4)
%rollingDiskKinematicRates
%    OUT1 = rollingDiskKinematicRates(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    10-Feb-2024 23:26:29

psi = in1(3,:);
r = in4(3,:);
u_1 = in2(1,:);
u_3 = in2(3,:);
u_dot_1 = in3(1,:);
u_dot_2 = in3(2,:);
u_dot_3 = in3(3,:);
t2 = cos(psi);
t3 = sin(psi);
out1 = [r.*t2.*u_dot_3-r.*t3.*u_1.*u_3;r.*t3.*u_dot_3+r.*t2.*u_1.*u_3;u_dot_1;u_dot_2;u_dot_3];
