function Jacf = centAccelJacobian(in1)
%centAccelJacobian
%    Jacf = centAccelJacobian(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    18-Jul-2025 01:49:52

V = in1(15,:);
varepsilon = in1(60,:);
Jacf = [0.0,0.0,0.0,0.0,0.0,V,0.0,0.0,V.*cos(varepsilon)];
end
