function f = roadRelativeKinematicsForcingVector(in1,in2,in3)
%roadRelativeKinematicsForcingVector
%    F = roadRelativeKinematicsForcingVector(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    18-Jul-2025 14:39:55

%   states = [s xi d]
%   inputs = [v_rx omega_r omega_f varphi delta omega_bz v_ry omega_bx omega_delta]
%   params = [kappa rho_r]
%
d = in1(3,:);
kappa = in3(1,:);
omega_bx = in2(8,:);
omega_bz = in2(6,:);
rho_r = in3(2,:);
v_rx = in2(1,:);
v_ry = in2(7,:);
xi = in1(2,:);
t2 = cos(xi);
t3 = sin(xi);
t4 = d.*kappa;
t5 = t4-1.0;
t6 = 1.0./t5;
f = [t6.*(-t2.*v_rx+t3.*v_ry+omega_bx.*rho_r.*t3);-t6.*(omega_bz-omega_bz.*t4-kappa.*t2.*v_rx+kappa.*t3.*v_ry+kappa.*omega_bx.*rho_r.*t3);t2.*v_ry+t3.*v_rx+omega_bx.*rho_r.*t2];
end
