function Jcamber = camberJacobian(in1)
%camberJacobian
%    Jcamber = camberJacobian(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    15-Jul-2025 10:07:29

varepsilon = in1(60,:);
Jcamber = reshape([0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,-sin(varepsilon),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[2,9]);
end
