function R = inputCost(in1,in2)
%inputCost
%    R = inputCost(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    22-Jul-2025 07:38:04

w_b = in2(2,:);
w_str = in2(3,:);
w_th = in2(1,:);
R = reshape([w_th,0.0,0.0,0.0,w_b,0.0,0.0,0.0,w_str],[3,3]);
end
