function x0 = stateCostTrim(in1,in2)
%stateCostTrim
%    X0 = stateCostTrim(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    22-Jul-2025 07:38:04

V = in1(15,:);
rho_f = in1(56,:);
rho_r = in1(57,:);
t_f = in1(58,:);
t_r = in1(59,:);
x0 = [V;V./(rho_r+t_r);V./(rho_f+t_f);0.0;0.0;0.0;0.0;0.0;0.0];
end
