function out1 = sharpMotorcycleLPVInputMatrix(in1,in2,in3)
%sharpMotorcycleLPVInputMatrix
%    OUT1 = sharpMotorcycleLPVInputMatrix(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    05-Mar-2024 14:14:56

V = in2(1,:);
d = in1(1,:);
kappa = in2(2,:);
xi = in1(2,:);
out1 = [0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;-(d.*kappa-1.0)./(V.*cos(xi))];
