function Bs = sharpMotorcycleLPVInputMatrix(in1)
%sharpMotorcycleLPVInputMatrix
%    Bs = sharpMotorcycleLPVInputMatrix(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    21-Feb-2024 09:42:04

V = in1(1,:);
d = in1(2,:);
kappa = in1(4,:);
xi = in1(3,:);
t2 = cos(xi);
t3 = d.*kappa;
t4 = 1.0./V;
t5 = 1.0./t2;
t6 = t3-1.0;
Bs = [0.0;0.0;0.0;0.0;t4.*t5.*t6.*(-8.545765733847499e-3);t4.*t5.*t6.*5.518052273191522e-2;t4.*t5.*t6.*1.605575016358991e-2;t4.*t5.*t6.*(-2.302813483966168);0.0;0.0];
