function Bs = sharpMotorcycleLPVInputMatrix(V,d,xi,kappa)
%sharpMotorcycleLPVInputMatrix
%    Bs = sharpMotorcycleLPVInputMatrix(V,D,XI,KAPPA)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    20-Feb-2024 16:03:22

t2 = cos(xi);
t3 = d.*kappa;
t4 = 1.0./V;
t5 = 1.0./t2;
t6 = t3-1.0;
Bs = [0.0;0.0;0.0;0.0;t4.*t5.*t6.*(-8.545765733847499e-3);t4.*t5.*t6.*5.518052273191522e-2;t4.*t5.*t6.*1.605575016358991e-2;t4.*t5.*t6.*(-2.302813483966168);0.0;0.0];
