function Bs = sharpMotorcycleLPVInputMatrix(in1)
%sharpMotorcycleLPVInputMatrix
%    Bs = sharpMotorcycleLPVInputMatrix(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    20-Feb-2024 21:27:27

V = in1(1,:);
d = in1(2,:);
kappa = in1(4,:);
xi = in1(3,:);
Bs = [0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;-(d.*kappa-1.0)./(V.*cos(xi))];
