function out1 = roadRelativeKinematics(in1,in2,kappa)
%roadRelativeKinematics
%    OUT1 = roadRelativeKinematics(IN1,IN2,KAPPA)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    06-Mar-2024 17:34:15

%    states = [s(t) d(t) xi(t)]
%    inputs = [v_x(t) v_y(t) omega_psi(t)]
%    params = [kappa]
%
d = in1(2,:);
omega_psi = in2(3,:);
v_x = in2(1,:);
v_y = in2(2,:);
xi = in1(3,:);
t2 = cos(xi);
t3 = sin(xi);
t4 = d.*kappa;
t5 = t4-1.0;
t6 = 1.0./t5;
out1 = [-t6.*(t2.*v_x-t3.*v_y);t3.*v_x+t2.*v_y;omega_psi+t6.*(kappa.*t2.*v_x-kappa.*t3.*v_y)];
