function out1 = noSlipVehicleInputMatrix(in1,in2)
%noSlipVehicleInputMatrix
%    OUT1 = noSlipVehicleInputMatrix(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    02-Jul-2024 05:28:07

I_zz = in2(1,:);
d = in1(1,:);
kappa = in2(2,:);
m = in2(3,:);
v_x = in1(3,:);
t2 = d.*kappa;
t3 = 1.0./v_x;
t4 = t2-1.0;
out1 = reshape([0.0,0.0,-(t3.*t4)./m,0.0,0.0,0.0,0.0,-(t3.*t4)./I_zz],[4,2]);
