function out1 = noSlipVehicleStateMatrix(in1,in2)
%noSlipVehicleStateMatrix
%    OUT1 = noSlipVehicleStateMatrix(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    02-Jul-2024 05:28:07

d = in1(1,:);
kappa = in2(2,:);
v_x = in1(3,:);
t2 = d.*kappa;
t3 = 1.0./v_x;
t4 = t2-1.0;
out1 = reshape([0.0,kappa.^2./t4,0.0,0.0,-t4,0.0,0.0,0.0,0.0,-kappa.*t3,0.0,0.0,0.0,-t3.*t4,0.0,0.0],[4,4]);
