function out1 = noSlipVehicleMeasuredDisturbance(in1,in2)
%noSlipVehicleMeasuredDisturbance
%    OUT1 = noSlipVehicleMeasuredDisturbance(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    02-Jul-2024 05:28:08

d = in1(1,:);
kappa = in2(2,:);
t2 = d.*kappa;
out1 = [0.0;-(kappa.*t2)./(t2-1.0);0.0;0.0];
