function M = roadRelativeKinematicsMassMatrix(in1,in2,in3)
%roadRelativeKinematicsMassMatrix
%    M = roadRelativeKinematicsMassMatrix(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    18-Jul-2025 14:39:55

%   states = [s xi d]
%   inputs = [v_rx omega_r omega_f varphi delta omega_bz v_ry omega_bx omega_delta]
%   params = [kappa rho_r]
%
M = reshape([1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0],[3,3]);
end
